### ISSUE TITLE
Cannot be downloaded mecab during the auto installation

### ISSUE THREAD

**Issue by kemuridama** [kazuhira-r/kuromoji-with-mecab-neologd-buildscript#1]
I occurred the below error trying to build Atilika Kuromoji with mecab-ipadic-neologd.

```
### [2017-05-21 12:43:57] [mecab] [INFO] MeCab Install Local.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1585  100  1585    0     0   1995      0 --:--:-- --:--:-- --:--:--  1996
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

https://mecab.googlecode.com has gone as Google Code service terminated.
That download page has moved in [Google Drive](https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE).
See also http://taku910.github.io/mecab/#download.

**Comment by kazuhira-r** [comment]
Thanks! @kemuridama
I fixed this problem.

However, since MeCab's download URL has changed several times, I plan to delete MeCab automatic installation someday from this script.
